// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_CREATEVEHICLE_VENERIS_COMMUNICATIONS_H_
#define FLATBUFFERS_GENERATED_CREATEVEHICLE_VENERIS_COMMUNICATIONS_H_

#include "flatbuffers/flatbuffers.h"

#include "BaseTypes_generated.h"

namespace Veneris {
namespace Communications {

struct CreateVehicle;
struct CreateVehicleBuilder;

struct CreateVehicle FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef CreateVehicleBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_POSITION = 6,
    VT_POLARIZATION = 8,
    VT_RADIUS = 10
  };
  uint32_t id() const {
    return GetField<uint32_t>(VT_ID, 0);
  }
  const Veneris::Communications::Vec3 *position() const {
    return GetStruct<const Veneris::Communications::Vec3 *>(VT_POSITION);
  }
  const Veneris::Communications::Vec3 *polarization() const {
    return GetStruct<const Veneris::Communications::Vec3 *>(VT_POLARIZATION);
  }
  float radius() const {
    return GetField<float>(VT_RADIUS, 0.0f);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_ID) &&
           VerifyField<Veneris::Communications::Vec3>(verifier, VT_POSITION) &&
           VerifyField<Veneris::Communications::Vec3>(verifier, VT_POLARIZATION) &&
           VerifyField<float>(verifier, VT_RADIUS) &&
           verifier.EndTable();
  }
};

struct CreateVehicleBuilder {
  typedef CreateVehicle Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_id(uint32_t id) {
    fbb_.AddElement<uint32_t>(CreateVehicle::VT_ID, id, 0);
  }
  void add_position(const Veneris::Communications::Vec3 *position) {
    fbb_.AddStruct(CreateVehicle::VT_POSITION, position);
  }
  void add_polarization(const Veneris::Communications::Vec3 *polarization) {
    fbb_.AddStruct(CreateVehicle::VT_POLARIZATION, polarization);
  }
  void add_radius(float radius) {
    fbb_.AddElement<float>(CreateVehicle::VT_RADIUS, radius, 0.0f);
  }
  explicit CreateVehicleBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<CreateVehicle> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<CreateVehicle>(end);
    return o;
  }
};

inline flatbuffers::Offset<CreateVehicle> CreateCreateVehicle(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t id = 0,
    const Veneris::Communications::Vec3 *position = 0,
    const Veneris::Communications::Vec3 *polarization = 0,
    float radius = 0.0f) {
  CreateVehicleBuilder builder_(_fbb);
  builder_.add_radius(radius);
  builder_.add_polarization(polarization);
  builder_.add_position(position);
  builder_.add_id(id);
  return builder_.Finish();
}

inline const Veneris::Communications::CreateVehicle *GetCreateVehicle(const void *buf) {
  return flatbuffers::GetRoot<Veneris::Communications::CreateVehicle>(buf);
}

inline const Veneris::Communications::CreateVehicle *GetSizePrefixedCreateVehicle(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<Veneris::Communications::CreateVehicle>(buf);
}

inline bool VerifyCreateVehicleBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<Veneris::Communications::CreateVehicle>(nullptr);
}

inline bool VerifySizePrefixedCreateVehicleBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<Veneris::Communications::CreateVehicle>(nullptr);
}

inline void FinishCreateVehicleBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<Veneris::Communications::CreateVehicle> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedCreateVehicleBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<Veneris::Communications::CreateVehicle> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace Communications
}  // namespace Veneris

#endif  // FLATBUFFERS_GENERATED_CREATEVEHICLE_VENERIS_COMMUNICATIONS_H_
