// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_FINISHDYNAMICMESHGROUP_VENERIS_COMMUNICATIONS_H_
#define FLATBUFFERS_GENERATED_FINISHDYNAMICMESHGROUP_VENERIS_COMMUNICATIONS_H_

#include "flatbuffers/flatbuffers.h"

#include "BaseTypes_generated.h"

namespace Veneris {
namespace Communications {

struct FinishDynamicMeshGroup;
struct FinishDynamicMeshGroupBuilder;

struct FinishDynamicMeshGroup FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef FinishDynamicMeshGroupBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4
  };
  int32_t id() const {
    return GetField<int32_t>(VT_ID, 0);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_ID) &&
           verifier.EndTable();
  }
};

struct FinishDynamicMeshGroupBuilder {
  typedef FinishDynamicMeshGroup Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_id(int32_t id) {
    fbb_.AddElement<int32_t>(FinishDynamicMeshGroup::VT_ID, id, 0);
  }
  explicit FinishDynamicMeshGroupBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<FinishDynamicMeshGroup> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<FinishDynamicMeshGroup>(end);
    return o;
  }
};

inline flatbuffers::Offset<FinishDynamicMeshGroup> CreateFinishDynamicMeshGroup(
    flatbuffers::FlatBufferBuilder &_fbb,
    int32_t id = 0) {
  FinishDynamicMeshGroupBuilder builder_(_fbb);
  builder_.add_id(id);
  return builder_.Finish();
}

inline const Veneris::Communications::FinishDynamicMeshGroup *GetFinishDynamicMeshGroup(const void *buf) {
  return flatbuffers::GetRoot<Veneris::Communications::FinishDynamicMeshGroup>(buf);
}

inline const Veneris::Communications::FinishDynamicMeshGroup *GetSizePrefixedFinishDynamicMeshGroup(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<Veneris::Communications::FinishDynamicMeshGroup>(buf);
}

inline bool VerifyFinishDynamicMeshGroupBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<Veneris::Communications::FinishDynamicMeshGroup>(nullptr);
}

inline bool VerifySizePrefixedFinishDynamicMeshGroupBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<Veneris::Communications::FinishDynamicMeshGroup>(nullptr);
}

inline void FinishFinishDynamicMeshGroupBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<Veneris::Communications::FinishDynamicMeshGroup> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedFinishDynamicMeshGroupBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<Veneris::Communications::FinishDynamicMeshGroup> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace Communications
}  // namespace Veneris

#endif  // FLATBUFFERS_GENERATED_FINISHDYNAMICMESHGROUP_VENERIS_COMMUNICATIONS_H_
