// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_RDNRAYRANGE_VENERIS_COMMUNICATIONS_H_
#define FLATBUFFERS_GENERATED_RDNRAYRANGE_VENERIS_COMMUNICATIONS_H_

#include "flatbuffers/flatbuffers.h"

#include "BaseTypes_generated.h"

namespace Veneris {
namespace Communications {

struct RDNRayRange;
struct RDNRayRangeBuilder;

struct RDNRayRange FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef RDNRayRangeBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_INITELEVATION = 4,
    VT_ENDELEVATION = 6,
    VT_INITAZIMUTH = 8,
    VT_ENDAZIMUTH = 10,
    VT_RAYD = 12
  };
  float initElevation() const {
    return GetField<float>(VT_INITELEVATION, 0.0f);
  }
  float endElevation() const {
    return GetField<float>(VT_ENDELEVATION, 0.0f);
  }
  float initAzimuth() const {
    return GetField<float>(VT_INITAZIMUTH, 0.0f);
  }
  float endAzimuth() const {
    return GetField<float>(VT_ENDAZIMUTH, 0.0f);
  }
  int32_t rayD() const {
    return GetField<int32_t>(VT_RAYD, 0);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<float>(verifier, VT_INITELEVATION) &&
           VerifyField<float>(verifier, VT_ENDELEVATION) &&
           VerifyField<float>(verifier, VT_INITAZIMUTH) &&
           VerifyField<float>(verifier, VT_ENDAZIMUTH) &&
           VerifyField<int32_t>(verifier, VT_RAYD) &&
           verifier.EndTable();
  }
};

struct RDNRayRangeBuilder {
  typedef RDNRayRange Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_initElevation(float initElevation) {
    fbb_.AddElement<float>(RDNRayRange::VT_INITELEVATION, initElevation, 0.0f);
  }
  void add_endElevation(float endElevation) {
    fbb_.AddElement<float>(RDNRayRange::VT_ENDELEVATION, endElevation, 0.0f);
  }
  void add_initAzimuth(float initAzimuth) {
    fbb_.AddElement<float>(RDNRayRange::VT_INITAZIMUTH, initAzimuth, 0.0f);
  }
  void add_endAzimuth(float endAzimuth) {
    fbb_.AddElement<float>(RDNRayRange::VT_ENDAZIMUTH, endAzimuth, 0.0f);
  }
  void add_rayD(int32_t rayD) {
    fbb_.AddElement<int32_t>(RDNRayRange::VT_RAYD, rayD, 0);
  }
  explicit RDNRayRangeBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<RDNRayRange> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<RDNRayRange>(end);
    return o;
  }
};

inline flatbuffers::Offset<RDNRayRange> CreateRDNRayRange(
    flatbuffers::FlatBufferBuilder &_fbb,
    float initElevation = 0.0f,
    float endElevation = 0.0f,
    float initAzimuth = 0.0f,
    float endAzimuth = 0.0f,
    int32_t rayD = 0) {
  RDNRayRangeBuilder builder_(_fbb);
  builder_.add_rayD(rayD);
  builder_.add_endAzimuth(endAzimuth);
  builder_.add_initAzimuth(initAzimuth);
  builder_.add_endElevation(endElevation);
  builder_.add_initElevation(initElevation);
  return builder_.Finish();
}

inline const Veneris::Communications::RDNRayRange *GetRDNRayRange(const void *buf) {
  return flatbuffers::GetRoot<Veneris::Communications::RDNRayRange>(buf);
}

inline const Veneris::Communications::RDNRayRange *GetSizePrefixedRDNRayRange(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<Veneris::Communications::RDNRayRange>(buf);
}

inline bool VerifyRDNRayRangeBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<Veneris::Communications::RDNRayRange>(nullptr);
}

inline bool VerifySizePrefixedRDNRayRangeBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<Veneris::Communications::RDNRayRange>(nullptr);
}

inline void FinishRDNRayRangeBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<Veneris::Communications::RDNRayRange> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedRDNRayRangeBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<Veneris::Communications::RDNRayRange> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace Communications
}  // namespace Veneris

#endif  // FLATBUFFERS_GENERATED_RDNRAYRANGE_VENERIS_COMMUNICATIONS_H_
