// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_REGISTERRECEIVERGAIN_VENERIS_COMMUNICATIONS_H_
#define FLATBUFFERS_GENERATED_REGISTERRECEIVERGAIN_VENERIS_COMMUNICATIONS_H_

#include "flatbuffers/flatbuffers.h"

#include "BaseTypes_generated.h"

namespace Veneris {
namespace Communications {

struct RegisterReceiverGain;
struct RegisterReceiverGainBuilder;

struct RegisterReceiverGain FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef RegisterReceiverGainBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_RXID = 4,
    VT_GAINID = 6
  };
  int32_t rxId() const {
    return GetField<int32_t>(VT_RXID, 0);
  }
  int32_t gainId() const {
    return GetField<int32_t>(VT_GAINID, 0);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_RXID) &&
           VerifyField<int32_t>(verifier, VT_GAINID) &&
           verifier.EndTable();
  }
};

struct RegisterReceiverGainBuilder {
  typedef RegisterReceiverGain Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_rxId(int32_t rxId) {
    fbb_.AddElement<int32_t>(RegisterReceiverGain::VT_RXID, rxId, 0);
  }
  void add_gainId(int32_t gainId) {
    fbb_.AddElement<int32_t>(RegisterReceiverGain::VT_GAINID, gainId, 0);
  }
  explicit RegisterReceiverGainBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<RegisterReceiverGain> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<RegisterReceiverGain>(end);
    return o;
  }
};

inline flatbuffers::Offset<RegisterReceiverGain> CreateRegisterReceiverGain(
    flatbuffers::FlatBufferBuilder &_fbb,
    int32_t rxId = 0,
    int32_t gainId = 0) {
  RegisterReceiverGainBuilder builder_(_fbb);
  builder_.add_gainId(gainId);
  builder_.add_rxId(rxId);
  return builder_.Finish();
}

inline const Veneris::Communications::RegisterReceiverGain *GetRegisterReceiverGain(const void *buf) {
  return flatbuffers::GetRoot<Veneris::Communications::RegisterReceiverGain>(buf);
}

inline const Veneris::Communications::RegisterReceiverGain *GetSizePrefixedRegisterReceiverGain(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<Veneris::Communications::RegisterReceiverGain>(buf);
}

inline bool VerifyRegisterReceiverGainBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<Veneris::Communications::RegisterReceiverGain>(nullptr);
}

inline bool VerifySizePrefixedRegisterReceiverGainBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<Veneris::Communications::RegisterReceiverGain>(nullptr);
}

inline void FinishRegisterReceiverGainBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<Veneris::Communications::RegisterReceiverGain> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedRegisterReceiverGainBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<Veneris::Communications::RegisterReceiverGain> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace Communications
}  // namespace Veneris

#endif  // FLATBUFFERS_GENERATED_REGISTERRECEIVERGAIN_VENERIS_COMMUNICATIONS_H_
