// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_STATICCURVEDMESH_VENERIS_COMMUNICATIONS_H_
#define FLATBUFFERS_GENERATED_STATICCURVEDMESH_VENERIS_COMMUNICATIONS_H_

#include "flatbuffers/flatbuffers.h"

#include "BaseTypes_generated.h"

namespace Veneris {
namespace Communications {

struct StaticCurvedMesh;
struct StaticCurvedMeshBuilder;

struct StaticCurvedMesh FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef StaticCurvedMeshBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TRANSFORM = 4,
    VT_VERTICES = 6,
    VT_INDEXES = 8,
    VT_MATERIAL = 10,
    VT_PD1 = 12,
    VT_PD2 = 14,
    VT_SINGLEFACE = 16,
    VT_FACEID = 18
  };
  const Veneris::Communications::Matrix4x4 *transform() const {
    return GetStruct<const Veneris::Communications::Matrix4x4 *>(VT_TRANSFORM);
  }
  const flatbuffers::Vector<const Veneris::Communications::Vec3 *> *vertices() const {
    return GetPointer<const flatbuffers::Vector<const Veneris::Communications::Vec3 *> *>(VT_VERTICES);
  }
  const flatbuffers::Vector<int32_t> *indexes() const {
    return GetPointer<const flatbuffers::Vector<int32_t> *>(VT_INDEXES);
  }
  const Veneris::Communications::MaterialEMP *material() const {
    return GetStruct<const Veneris::Communications::MaterialEMP *>(VT_MATERIAL);
  }
  const flatbuffers::Vector<const Veneris::Communications::Vec4 *> *pd1() const {
    return GetPointer<const flatbuffers::Vector<const Veneris::Communications::Vec4 *> *>(VT_PD1);
  }
  const flatbuffers::Vector<const Veneris::Communications::Vec4 *> *pd2() const {
    return GetPointer<const flatbuffers::Vector<const Veneris::Communications::Vec4 *> *>(VT_PD2);
  }
  bool singleFace() const {
    return GetField<uint8_t>(VT_SINGLEFACE, 0) != 0;
  }
  int32_t faceId() const {
    return GetField<int32_t>(VT_FACEID, 0);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<Veneris::Communications::Matrix4x4>(verifier, VT_TRANSFORM) &&
           VerifyOffset(verifier, VT_VERTICES) &&
           verifier.VerifyVector(vertices()) &&
           VerifyOffset(verifier, VT_INDEXES) &&
           verifier.VerifyVector(indexes()) &&
           VerifyField<Veneris::Communications::MaterialEMP>(verifier, VT_MATERIAL) &&
           VerifyOffset(verifier, VT_PD1) &&
           verifier.VerifyVector(pd1()) &&
           VerifyOffset(verifier, VT_PD2) &&
           verifier.VerifyVector(pd2()) &&
           VerifyField<uint8_t>(verifier, VT_SINGLEFACE) &&
           VerifyField<int32_t>(verifier, VT_FACEID) &&
           verifier.EndTable();
  }
};

struct StaticCurvedMeshBuilder {
  typedef StaticCurvedMesh Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_transform(const Veneris::Communications::Matrix4x4 *transform) {
    fbb_.AddStruct(StaticCurvedMesh::VT_TRANSFORM, transform);
  }
  void add_vertices(flatbuffers::Offset<flatbuffers::Vector<const Veneris::Communications::Vec3 *>> vertices) {
    fbb_.AddOffset(StaticCurvedMesh::VT_VERTICES, vertices);
  }
  void add_indexes(flatbuffers::Offset<flatbuffers::Vector<int32_t>> indexes) {
    fbb_.AddOffset(StaticCurvedMesh::VT_INDEXES, indexes);
  }
  void add_material(const Veneris::Communications::MaterialEMP *material) {
    fbb_.AddStruct(StaticCurvedMesh::VT_MATERIAL, material);
  }
  void add_pd1(flatbuffers::Offset<flatbuffers::Vector<const Veneris::Communications::Vec4 *>> pd1) {
    fbb_.AddOffset(StaticCurvedMesh::VT_PD1, pd1);
  }
  void add_pd2(flatbuffers::Offset<flatbuffers::Vector<const Veneris::Communications::Vec4 *>> pd2) {
    fbb_.AddOffset(StaticCurvedMesh::VT_PD2, pd2);
  }
  void add_singleFace(bool singleFace) {
    fbb_.AddElement<uint8_t>(StaticCurvedMesh::VT_SINGLEFACE, static_cast<uint8_t>(singleFace), 0);
  }
  void add_faceId(int32_t faceId) {
    fbb_.AddElement<int32_t>(StaticCurvedMesh::VT_FACEID, faceId, 0);
  }
  explicit StaticCurvedMeshBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<StaticCurvedMesh> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<StaticCurvedMesh>(end);
    return o;
  }
};

inline flatbuffers::Offset<StaticCurvedMesh> CreateStaticCurvedMesh(
    flatbuffers::FlatBufferBuilder &_fbb,
    const Veneris::Communications::Matrix4x4 *transform = 0,
    flatbuffers::Offset<flatbuffers::Vector<const Veneris::Communications::Vec3 *>> vertices = 0,
    flatbuffers::Offset<flatbuffers::Vector<int32_t>> indexes = 0,
    const Veneris::Communications::MaterialEMP *material = 0,
    flatbuffers::Offset<flatbuffers::Vector<const Veneris::Communications::Vec4 *>> pd1 = 0,
    flatbuffers::Offset<flatbuffers::Vector<const Veneris::Communications::Vec4 *>> pd2 = 0,
    bool singleFace = false,
    int32_t faceId = 0) {
  StaticCurvedMeshBuilder builder_(_fbb);
  builder_.add_faceId(faceId);
  builder_.add_pd2(pd2);
  builder_.add_pd1(pd1);
  builder_.add_material(material);
  builder_.add_indexes(indexes);
  builder_.add_vertices(vertices);
  builder_.add_transform(transform);
  builder_.add_singleFace(singleFace);
  return builder_.Finish();
}

inline flatbuffers::Offset<StaticCurvedMesh> CreateStaticCurvedMeshDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const Veneris::Communications::Matrix4x4 *transform = 0,
    const std::vector<Veneris::Communications::Vec3> *vertices = nullptr,
    const std::vector<int32_t> *indexes = nullptr,
    const Veneris::Communications::MaterialEMP *material = 0,
    const std::vector<Veneris::Communications::Vec4> *pd1 = nullptr,
    const std::vector<Veneris::Communications::Vec4> *pd2 = nullptr,
    bool singleFace = false,
    int32_t faceId = 0) {
  auto vertices__ = vertices ? _fbb.CreateVectorOfStructs<Veneris::Communications::Vec3>(*vertices) : 0;
  auto indexes__ = indexes ? _fbb.CreateVector<int32_t>(*indexes) : 0;
  auto pd1__ = pd1 ? _fbb.CreateVectorOfStructs<Veneris::Communications::Vec4>(*pd1) : 0;
  auto pd2__ = pd2 ? _fbb.CreateVectorOfStructs<Veneris::Communications::Vec4>(*pd2) : 0;
  return Veneris::Communications::CreateStaticCurvedMesh(
      _fbb,
      transform,
      vertices__,
      indexes__,
      material,
      pd1__,
      pd2__,
      singleFace,
      faceId);
}

inline const Veneris::Communications::StaticCurvedMesh *GetStaticCurvedMesh(const void *buf) {
  return flatbuffers::GetRoot<Veneris::Communications::StaticCurvedMesh>(buf);
}

inline const Veneris::Communications::StaticCurvedMesh *GetSizePrefixedStaticCurvedMesh(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<Veneris::Communications::StaticCurvedMesh>(buf);
}

inline bool VerifyStaticCurvedMeshBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<Veneris::Communications::StaticCurvedMesh>(nullptr);
}

inline bool VerifySizePrefixedStaticCurvedMeshBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<Veneris::Communications::StaticCurvedMesh>(nullptr);
}

inline void FinishStaticCurvedMeshBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<Veneris::Communications::StaticCurvedMesh> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedStaticCurvedMeshBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<Veneris::Communications::StaticCurvedMesh> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace Communications
}  // namespace Veneris

#endif  // FLATBUFFERS_GENERATED_STATICCURVEDMESH_VENERIS_COMMUNICATIONS_H_
