// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_STATICMESH_VENERIS_COMMUNICATIONS_H_
#define FLATBUFFERS_GENERATED_STATICMESH_VENERIS_COMMUNICATIONS_H_

#include "flatbuffers/flatbuffers.h"

#include "BaseTypes_generated.h"

namespace Veneris {
namespace Communications {

struct StaticMesh;
struct StaticMeshBuilder;

struct StaticMesh FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef StaticMeshBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TRANSFORM = 4,
    VT_VERTICES = 6,
    VT_INDEXES = 8,
    VT_MATERIAL = 10
  };
  const Veneris::Communications::Matrix4x4 *transform() const {
    return GetStruct<const Veneris::Communications::Matrix4x4 *>(VT_TRANSFORM);
  }
  const flatbuffers::Vector<const Veneris::Communications::Vec3 *> *vertices() const {
    return GetPointer<const flatbuffers::Vector<const Veneris::Communications::Vec3 *> *>(VT_VERTICES);
  }
  const flatbuffers::Vector<int32_t> *indexes() const {
    return GetPointer<const flatbuffers::Vector<int32_t> *>(VT_INDEXES);
  }
  const Veneris::Communications::MaterialEMP *material() const {
    return GetStruct<const Veneris::Communications::MaterialEMP *>(VT_MATERIAL);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<Veneris::Communications::Matrix4x4>(verifier, VT_TRANSFORM) &&
           VerifyOffset(verifier, VT_VERTICES) &&
           verifier.VerifyVector(vertices()) &&
           VerifyOffset(verifier, VT_INDEXES) &&
           verifier.VerifyVector(indexes()) &&
           VerifyField<Veneris::Communications::MaterialEMP>(verifier, VT_MATERIAL) &&
           verifier.EndTable();
  }
};

struct StaticMeshBuilder {
  typedef StaticMesh Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_transform(const Veneris::Communications::Matrix4x4 *transform) {
    fbb_.AddStruct(StaticMesh::VT_TRANSFORM, transform);
  }
  void add_vertices(flatbuffers::Offset<flatbuffers::Vector<const Veneris::Communications::Vec3 *>> vertices) {
    fbb_.AddOffset(StaticMesh::VT_VERTICES, vertices);
  }
  void add_indexes(flatbuffers::Offset<flatbuffers::Vector<int32_t>> indexes) {
    fbb_.AddOffset(StaticMesh::VT_INDEXES, indexes);
  }
  void add_material(const Veneris::Communications::MaterialEMP *material) {
    fbb_.AddStruct(StaticMesh::VT_MATERIAL, material);
  }
  explicit StaticMeshBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<StaticMesh> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<StaticMesh>(end);
    return o;
  }
};

inline flatbuffers::Offset<StaticMesh> CreateStaticMesh(
    flatbuffers::FlatBufferBuilder &_fbb,
    const Veneris::Communications::Matrix4x4 *transform = 0,
    flatbuffers::Offset<flatbuffers::Vector<const Veneris::Communications::Vec3 *>> vertices = 0,
    flatbuffers::Offset<flatbuffers::Vector<int32_t>> indexes = 0,
    const Veneris::Communications::MaterialEMP *material = 0) {
  StaticMeshBuilder builder_(_fbb);
  builder_.add_material(material);
  builder_.add_indexes(indexes);
  builder_.add_vertices(vertices);
  builder_.add_transform(transform);
  return builder_.Finish();
}

inline flatbuffers::Offset<StaticMesh> CreateStaticMeshDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const Veneris::Communications::Matrix4x4 *transform = 0,
    const std::vector<Veneris::Communications::Vec3> *vertices = nullptr,
    const std::vector<int32_t> *indexes = nullptr,
    const Veneris::Communications::MaterialEMP *material = 0) {
  auto vertices__ = vertices ? _fbb.CreateVectorOfStructs<Veneris::Communications::Vec3>(*vertices) : 0;
  auto indexes__ = indexes ? _fbb.CreateVector<int32_t>(*indexes) : 0;
  return Veneris::Communications::CreateStaticMesh(
      _fbb,
      transform,
      vertices__,
      indexes__,
      material);
}

inline const Veneris::Communications::StaticMesh *GetStaticMesh(const void *buf) {
  return flatbuffers::GetRoot<Veneris::Communications::StaticMesh>(buf);
}

inline const Veneris::Communications::StaticMesh *GetSizePrefixedStaticMesh(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<Veneris::Communications::StaticMesh>(buf);
}

inline bool VerifyStaticMeshBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<Veneris::Communications::StaticMesh>(nullptr);
}

inline bool VerifySizePrefixedStaticMeshBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<Veneris::Communications::StaticMesh>(nullptr);
}

inline void FinishStaticMeshBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<Veneris::Communications::StaticMesh> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedStaticMeshBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<Veneris::Communications::StaticMesh> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace Communications
}  // namespace Veneris

#endif  // FLATBUFFERS_GENERATED_STATICMESH_VENERIS_COMMUNICATIONS_H_
