// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_UPDATETRANSFORMINGROUP_VENERIS_COMMUNICATIONS_H_
#define FLATBUFFERS_GENERATED_UPDATETRANSFORMINGROUP_VENERIS_COMMUNICATIONS_H_

#include "flatbuffers/flatbuffers.h"

#include "BaseTypes_generated.h"

namespace Veneris {
namespace Communications {

struct UpdateTransformInGroup;
struct UpdateTransformInGroupBuilder;

struct UpdateTransformInGroup FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef UpdateTransformInGroupBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_TRANSFORM = 6
  };
  int32_t id() const {
    return GetField<int32_t>(VT_ID, 0);
  }
  const Veneris::Communications::Matrix4x4 *transform() const {
    return GetStruct<const Veneris::Communications::Matrix4x4 *>(VT_TRANSFORM);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_ID) &&
           VerifyField<Veneris::Communications::Matrix4x4>(verifier, VT_TRANSFORM) &&
           verifier.EndTable();
  }
};

struct UpdateTransformInGroupBuilder {
  typedef UpdateTransformInGroup Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_id(int32_t id) {
    fbb_.AddElement<int32_t>(UpdateTransformInGroup::VT_ID, id, 0);
  }
  void add_transform(const Veneris::Communications::Matrix4x4 *transform) {
    fbb_.AddStruct(UpdateTransformInGroup::VT_TRANSFORM, transform);
  }
  explicit UpdateTransformInGroupBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<UpdateTransformInGroup> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<UpdateTransformInGroup>(end);
    return o;
  }
};

inline flatbuffers::Offset<UpdateTransformInGroup> CreateUpdateTransformInGroup(
    flatbuffers::FlatBufferBuilder &_fbb,
    int32_t id = 0,
    const Veneris::Communications::Matrix4x4 *transform = 0) {
  UpdateTransformInGroupBuilder builder_(_fbb);
  builder_.add_transform(transform);
  builder_.add_id(id);
  return builder_.Finish();
}

inline const Veneris::Communications::UpdateTransformInGroup *GetUpdateTransformInGroup(const void *buf) {
  return flatbuffers::GetRoot<Veneris::Communications::UpdateTransformInGroup>(buf);
}

inline const Veneris::Communications::UpdateTransformInGroup *GetSizePrefixedUpdateTransformInGroup(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<Veneris::Communications::UpdateTransformInGroup>(buf);
}

inline bool VerifyUpdateTransformInGroupBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<Veneris::Communications::UpdateTransformInGroup>(nullptr);
}

inline bool VerifySizePrefixedUpdateTransformInGroupBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<Veneris::Communications::UpdateTransformInGroup>(nullptr);
}

inline void FinishUpdateTransformInGroupBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<Veneris::Communications::UpdateTransformInGroup> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedUpdateTransformInGroupBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<Veneris::Communications::UpdateTransformInGroup> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace Communications
}  // namespace Veneris

#endif  // FLATBUFFERS_GENERATED_UPDATETRANSFORMINGROUP_VENERIS_COMMUNICATIONS_H_
